name: Setup the Python Environment

on: workflow_call

jobs:
  setup:
    name: setup
    runs-on: ${{ matrix.os }}
    env:
      ZENML_DEBUG: 1
      ZENML_ANALYTICS_OPT_IN: false
      PYTHONIOENCODING: 'utf-8'
    # Exit if its a commit from Gitbook
    if: ${{ ! startsWith(github.event.head_commit.message, 'GitBook:') }}

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Setup environment with Poetry
        uses: ./.github/actions/setup_environment

      - name: Export venv location
        run: |
          # use bash variable expression to get the substring
          export GIT_PR_SHA="${{ github.sha }}"
          export GIT_PR_SHA_SHORT="${GIT_PR_SHA:0:10}"

          echo "::set-output name=git_pr_sha::${GIT_PR_SHA}"
          echo "::set-output name=git_pr_sha_short::${GIT_PR_SHA_SHORT}"
